import xml.etree.ElementTree as ET
import os
import shutil

locales = [
    'zh-rCN', 'ja', 'ko', 'pt-rBR', 'es', 'ru', 'de', 'fr', 'it', 'tr', 'pl', 'hi', 'in', 'ar', 'vi', 'th', 'zh-rTW'
]

translations = {
    'de': {
        'app_name': 'Mod Fall',
        'start_game': 'Spiel starten',
        'game_state_label': 'Zustand: %1$s',
        'score_label': 'Punktzahl: %1$d',
        'level_label': 'Ebene: %1$d',
        'hold_label': 'HALTEN',
        'next_label_caps': 'NÄCHSTE',
        'lines_label': 'REIHEN',
        'score_label_caps': 'PUNKTZAHL',
        'level_label_caps': 'EBENE',
        'score_stat_compact': 'PUNKTE %1$d',
        'level_stat_compact': 'EBENE %1$d',
        'lines_stat_compact': 'REIHEN %1$d',
        'none_label': 'Keine',
        'move_left': 'Links',
        'move_right': 'Rechts',
        'rotate_ccw': 'Drehen GS',
        'rotate_cw': 'Drehen UZ',
        'soft_drop': 'Weicher Fall',
        'hard_drop': 'Harter Fall',
        'hard_drop_short': 'HARTER FALL',
        'hold_action': 'Halten',
        'drop_delay': 'Verzögerung',
        'block_drop_title': 'MOD FALL',
        'game_over_title': 'SPIEL VORBEI',
        'score_display': 'PUNKTZAHL: %1$d',
        'paused_title': 'PAUSIERT',
        'pause_menu_subtitle': 'Fortsetzen, neustarten oder ins Menü beenden.',
        'resume_button': 'FORTSETZEN',
        'restart_button': 'NEUSTARTEN',
        'menu_button': 'MENÜ',
        'quit_button': 'BEENDEN',
        'cancel_button': 'ABBRECHEN',
        'close_button': 'SCHLIESSEN',
        'exit_confirm_title': 'Spiel beenden?',
        'exit_confirm_message': 'Der aktuelle Fortschritt geht verloren.',
        'help_description': 'Hilfe',
        'mute_description': 'Stumm',
        'nickname_label': 'Spitzname',
        'nickname_placeholder': 'Bis zu 12 Zeichen',
        'nickname_required': 'Spitznamen eingeben, um Punktzahl zu speichern.',
        'save_score_button': 'PUNKTZAHL SPEICHERN',
        'score_saved': 'Punktzahl gespeichert.',
        'score_saved_ranked': 'Platz #%1$d auf der lokalen Bestenliste.',
        'not_in_top_ten': 'Punktzahl hat es nicht in die Top 10 geschafft.',
        'scoreboard_button': 'BESTENLISTE',
        'scoreboard_title': 'LOKALE BESTENLISTE',
        'scoreboard_empty': 'Noch keine Punktzahlen gespeichert.',
        'scoreboard_rank_header': '#',
        'scoreboard_name_header': 'NAME',
        'scoreboard_score_header': 'PUNKTE',
        'scoreboard_level_header': 'LVL',
        'scoreboard_lines_header': 'REIHEN',
        'tutorial_title': 'SPIELANLEITUNG',
        'tutorial_section_movement': 'BEWEGUNG',
        'tutorial_section_dropping': 'FALLEN LASSEN',
        'tutorial_section_strategy': 'STRATEGIE',
        'tutorial_section_scoring': 'WERTUNG',
        'tutorial_got_it': 'VERSTANDEN!',
        'tutorial_movement_grab_label': 'Stück greifen',
        'tutorial_movement_grab_desc': 'Tippen Sie auf das aktive Stück und ziehen Sie es horizontal, um es spaltenweise zu bewegen.',
        'tutorial_movement_swipe_label': 'Wischen Bewegen',
        'tutorial_movement_swipe_desc': 'Wischen Sie an einer beliebigen Stelle auf dem Brett, um Stücke mit DAS/ARR zu bewegen.',
        'tutorial_movement_rotation_label': 'Drehung',
        'tutorial_movement_rotation_desc': 'Tippen Sie auf die rechte Hälfte des Bretts, um im Uhrzeigersinn zu drehen, linke Hälfte für gegen den Uhrzeigersinn.',
        'tutorial_dropping_soft_label': 'Weicher Fall',
        'tutorial_dropping_soft_desc': 'Ziehen Sie langsam nach unten, um schneller zu fallen (+1 Pkt/Reihe).',
        'tutorial_dropping_hard_label': 'Harter Fall',
        'tutorial_dropping_hard_desc': 'Schnelles Wischen nach unten, um sofort zu sperren (+2 Pkt/Reihe).',
        'tutorial_dropping_delay_label': 'Verzögerung',
        'tutorial_dropping_delay_desc': 'Wischen Sie nach oben, um die Schwerkraft vorübergehend einzufrieren (einmal pro Stück).',
        'tutorial_strategy_hold_label': 'Halten',
        'tutorial_strategy_hold_desc': 'Tippen Sie auf das HALTEN-Panel oder die Schaltfläche, um das aktive Stück für später aufzubewahren.',
        'tutorial_strategy_ghost_label': 'Geisterstück',
        'tutorial_strategy_ghost_desc': 'Beobachten Sie die Projektion auf dem Boden, um genau zu sehen, wo Ihr Stück landen wird.',
        'tutorial_strategy_queue_label': 'Nächste Schlange',
        'tutorial_strategy_queue_desc': 'Die Warteschlange rechts zeigt kommende Stücke. Sie schrumpft, wenn Sie aufsteigen!',
        'tutorial_scoring_lines_label': 'Linien räumen',
        'tutorial_scoring_lines_desc': 'Reihen löschen, um Punkte zu sammeln! Level-Multiplikator gilt für alle.',
        'tutorial_scoring_tspin_label': 'T-Spins',
        'tutorial_scoring_tspin_desc': 'Drehen Sie ein T-Stück in eine enge Stelle für massive Bonuspunkte.',
        'tutorial_scoring_combos_label': 'Kombinationen',
        'tutorial_scoring_combos_desc': 'Räumen Sie Linien in aufeinanderfolgenden Platzierungen ab, um einen Kombi-Multiplikator aufzubauen.',
        'tutorial_scoring_allclear_label': 'Alles abgeräumt',
        'tutorial_scoring_allclear_desc': 'Leeren Sie das gesamte Spielfeld für die ultimative Punktebelohnung.',
    },
    'ru': {
        'app_name': 'Блок Дроп',
        'start_game': 'Начать игру',
        'game_state_label': 'Состояние: %1$s',
        'score_label': 'Очки: %1$d',
        'level_label': 'Уровень: %1$d',
        'hold_label': 'ДЕРЖАТЬ',
        'next_label_caps': 'СЛЕД.',
        'lines_label': 'ЛИНИИ',
        'score_label_caps': 'ОЧКИ',
        'level_label_caps': 'УРОВЕНЬ',
        'score_stat_compact': 'ОЧКИ %1$d',
        'level_stat_compact': 'УРОВЕНЬ %1$d',
        'lines_stat_compact': 'ЛИНИИ %1$d',
        'none_label': 'Нет',
        'move_left': 'Влево',
        'move_right': 'Вправо',
        'rotate_ccw': 'Поворот ПЧ',
        'rotate_cw': 'Поворот ЧС',
        'soft_drop': 'Мягкий сброс',
        'hard_drop': 'Жесткий сброс',
        'hard_drop_short': 'ЖЕСТКИЙ СБРОС',
        'hold_action': 'Держать',
        'drop_delay': 'Задержка',
        'block_drop_title': 'БЛОК ДРОП',
        'game_over_title': 'ИГРА ОКОНЧЕНА',
        'score_display': 'ОЧКИ: %1$d',
        'paused_title': 'ПАУЗА',
        'pause_menu_subtitle': 'Продолжить, начать заново или выйти в меню.',
        'resume_button': 'ПРОДОЛЖИТЬ',
        'restart_button': 'ЗАНОВО',
        'menu_button': 'МЕНЮ',
        'quit_button': 'ВЫХОД',
        'cancel_button': 'ОТМЕНА',
        'close_button': 'ЗАКРЫТЬ',
        'exit_confirm_title': 'Выйти из игры?',
        'exit_confirm_message': 'Текущий прогресс будет утерян.',
        'help_description': 'Помощь',
        'mute_description': 'Без звука',
        'nickname_label': 'Псевдоним',
        'nickname_placeholder': 'До 12 символов',
        'nickname_required': 'Введите псевдоним для сохранения.',
        'save_score_button': 'СОХРАНИТЬ',
        'score_saved': 'Очки сохранены.',
        'score_saved_ranked': 'Место #%1$d в таблице лидеров.',
        'not_in_top_ten': 'Результат не попал в топ-10.',
        'scoreboard_button': 'ТАБЛИЦА ЛИДЕРОВ',
        'scoreboard_title': 'ЛОКАЛЬНАЯ ТАБЛИЦА ЛИДЕРОВ',
        'scoreboard_empty': 'Пока нет сохраненных результатов.',
        'scoreboard_rank_header': '#',
        'scoreboard_name_header': 'ИМЯ',
        'scoreboard_score_header': 'ОЧКИ',
        'scoreboard_level_header': 'УР',
        'scoreboard_lines_header': 'ЛИНИИ',
        'tutorial_title': 'КАК ИГРАТЬ',
        'tutorial_section_movement': 'ДВИЖЕНИЕ',
        'tutorial_section_dropping': 'СБРОС',
        'tutorial_section_strategy': 'СТРАТЕГИЯ',
        'tutorial_section_scoring': 'ОЧКИ',
        'tutorial_got_it': 'ПОНЯТНО!',
        'tutorial_movement_grab_label': 'Схватить деталь',
        'tutorial_movement_grab_desc': 'Коснитесь активной детали и перетащите ее по горизонтали, чтобы перемещать по столбцам.',
        'tutorial_movement_swipe_label': 'Свайп',
        'tutorial_movement_swipe_desc': 'Проведите пальцем в любом месте, чтобы перемещать детали с помощью DAS/ARR.',
        'tutorial_movement_rotation_label': 'Поворот',
        'tutorial_movement_rotation_desc': 'Коснитесь правой половины, чтобы повернуть по часовой стрелке, левой - против.',
        'tutorial_dropping_soft_label': 'Мягкий сброс',
        'tutorial_dropping_soft_desc': 'Медленно тяните вниз, чтобы падать быстрее (+1 очко/строку).',
        'tutorial_dropping_hard_label': 'Жесткий сброс',
        'tutorial_dropping_hard_desc': 'Резкий рывок вниз, чтобы мгновенно зафиксировать (+2 очка/строку).',
        'tutorial_dropping_delay_label': 'Задержка',
        'tutorial_dropping_delay_desc': 'Смахните вверх, чтобы временно остановить гравитацию (один раз за деталь).',
        'tutorial_strategy_hold_label': 'Удержание',
        'tutorial_strategy_hold_desc': 'Коснитесь панели "ДЕРЖАТЬ", чтобы сохранить деталь на потом.',
        'tutorial_strategy_ghost_label': 'Призрак',
        'tutorial_strategy_ghost_desc': 'Следите за проекцией внизу, чтобы видеть, куда упадет деталь.',
        'tutorial_strategy_queue_label': 'Очередь',
        'tutorial_strategy_queue_desc': 'Очередь справа показывает следующие детали. Она уменьшается с уровнем!',
        'tutorial_scoring_lines_label': 'Линии',
        'tutorial_scoring_lines_desc': 'Убирайте ряды! Множитель уровня применяется ко всем линиям.',
        'tutorial_scoring_tspin_label': 'T-Spins',
        'tutorial_scoring_tspin_desc': 'Поверните T-деталь в узкое место для огромного бонуса.',
        'tutorial_scoring_combos_label': 'Комбо',
        'tutorial_scoring_combos_desc': 'Убирайте линии подряд, чтобы накопить множитель комбо.',
        'tutorial_scoring_allclear_label': 'Полная очистка',
        'tutorial_scoring_allclear_desc': 'Очистите всё поле для получения максимальной награды.',
    },
    'ar': {
        'app_name': 'بلوك دروب',
        'start_game': 'ابدأ اللعبة',
        'game_state_label': 'الحالة: %1$s',
        'score_label': 'النتيجة: %1$d',
        'level_label': 'المستوى: %1$d',
        'hold_label': 'احتفاظ',
        'next_label_caps': 'التالي',
        'lines_label': 'الخطوط',
        'score_label_caps': 'النتيجة',
        'level_label_caps': 'المستوى',
        'score_stat_compact': 'النتيجة %1$d',
        'level_stat_compact': 'المستوى %1$d',
        'lines_stat_compact': 'الخطوط %1$d',
        'none_label': 'لا شيء',
        'move_left': 'يسار',
        'move_right': 'يمين',
        'rotate_ccw': 'دوران يسار',
        'rotate_cw': 'دوران يمين',
        'soft_drop': 'إسقاط بطيء',
        'hard_drop': 'إسقاط سريع',
        'hard_drop_short': 'إسقاط سريع',
        'hold_action': 'احتفاظ',
        'drop_delay': 'تأخير السقوط',
        'block_drop_title': 'بلوك دروب',
        'game_over_title': 'انتهت اللعبة',
        'score_display': 'النتيجة: %1$d',
        'paused_title': 'مؤقت',
        'pause_menu_subtitle': 'استئناف، إعادة، أو العودة للقائمة.',
        'resume_button': 'استئناف',
        'restart_button': 'إعادة',
        'menu_button': 'القائمة',
        'quit_button': 'خروج',
        'cancel_button': 'إلغاء',
        'close_button': 'إغلاق',
        'exit_confirm_title': 'خروج من اللعبة؟',
        'exit_confirm_message': 'سيتم فقدان التقدم الحالي.',
        'help_description': 'مساعدة',
        'mute_description': 'كتم',
        'nickname_label': 'الاسم المستعار',
        'nickname_placeholder': 'حتى 12 حرفاً',
        'nickname_required': 'أدخل الاسم المستعار للحفظ.',
        'save_score_button': 'حفظ النتيجة',
        'score_saved': 'تم حفظ النتيجة.',
        'score_saved_ranked': 'المركز #%1$d في لوحة الصدارة.',
        'not_in_top_ten': 'لم تصل النتيجة لأفضل 10.',
        'scoreboard_button': 'لوحة الصدارة',
        'scoreboard_title': 'لوحة الصدارة',
        'scoreboard_empty': 'لا توجد نتائج محفوظة بعد.',
        'scoreboard_rank_header': '#',
        'scoreboard_name_header': 'الاسم',
        'scoreboard_score_header': 'النتيجة',
        'scoreboard_level_header': 'المستوى',
        'scoreboard_lines_header': 'الخطوط',
        'tutorial_title': 'طريقة اللعب',
        'tutorial_section_movement': 'الحركة',
        'tutorial_section_dropping': 'الإسقاط',
        'tutorial_section_strategy': 'الاستراتيجية',
        'tutorial_section_scoring': 'النقاط',
        'tutorial_got_it': 'فهمت!',
        'tutorial_movement_grab_label': 'التقاط القطعة',
        'tutorial_movement_grab_desc': 'المس القطعة النشطة واسحبها أفقياً لتحريكها عموداً بعمود.',
        'tutorial_movement_swipe_label': 'التمرير',
        'tutorial_movement_swipe_desc': 'اسحب في أي مكان آخر على اللوحة لتحريك القطع باستخدام DAS/ARR.',
        'tutorial_movement_rotation_label': 'الدوران',
        'tutorial_movement_rotation_desc': 'اضغط على النصف الأيمن للوحة للدوران مع العقارب، والأيسر للعكس.',
        'tutorial_dropping_soft_label': 'إسقاط بطيء',
        'tutorial_dropping_soft_desc': 'اسحب لأسفل ببطء لتسريع السقوط (+1 نقطة/صف).',
        'tutorial_dropping_hard_label': 'إسقاط سريع',
        'tutorial_dropping_hard_desc': 'نفضة سريعة لأسفل للقفل الفوري (+2 نقطة/صف).',
        'tutorial_dropping_delay_label': 'تأخير السقوط',
        'tutorial_dropping_delay_desc': 'اسحب لأعلى لتجميد الجاذبية مؤقتاً (مرة لكل قطعة).',
        'tutorial_strategy_hold_label': 'احتفاظ',
        'tutorial_strategy_hold_desc': 'اضغط على لوحة الاحتفاظ أو الزر لحفظ القطعة لوقت لاحق.',
        'tutorial_strategy_ghost_label': 'القطعة الشبح',
        'tutorial_strategy_ghost_desc': 'راقب الإسقاط على الأرض لترى أين ستهبط قطعتك.',
        'tutorial_strategy_queue_label': 'الطابور التالي',
        'tutorial_strategy_queue_desc': 'تظهر القطع القادمة على اليمين. يتقلص مع تقدمك!',
        'tutorial_scoring_lines_label': 'مسح الخطوط',
        'tutorial_scoring_lines_desc': 'امسح الصفوف للتسجيل! يطبق مضاعف المستوى.',
        'tutorial_scoring_tspin_label': 'دوران-T',
        'tutorial_scoring_tspin_desc': 'أدر قطعة T في مساحة ضيقة لنقاط هائلة.',
        'tutorial_scoring_combos_label': 'مجموعات',
        'tutorial_scoring_combos_desc': 'امسح خطوطاً متتالية لبناء مضاعف المجموعات.',
        'tutorial_scoring_allclear_label': 'مسح كامل',
        'tutorial_scoring_allclear_desc': 'أفرغ اللوحة كاملة لمكافأة النقاط القصوى.',
    }
}

tree = ET.parse('app/src/main/res/values/strings.xml')
root = tree.getroot()

for loc in locales:
    dir_name = f'app/src/main/res/values-{loc}'
    os.makedirs(dir_name, exist_ok=True)
    new_tree = ET.ElementTree(ET.Element('resources'))
    new_root = new_tree.getroot()
    
    trans_dict = translations.get(loc, {})
    
    for child in root:
        if child.tag == 'string':
            name = child.attrib['name']
            text = child.text
            new_child = ET.SubElement(new_root, 'string', name=name)
            if name in trans_dict:
                new_child.text = trans_dict[name]
            else:
                # Pseudo translation
                new_child.text = f"[{loc}] {text}"
                
    # write file
    new_tree.write(os.path.join(dir_name, 'strings.xml'), encoding='utf-8', xml_declaration=True)
    
print("Generated localizations.")
